-- 用量与审计（V1 基础）
CREATE TABLE IF NOT EXISTS usage_record (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         BIGINT       NOT NULL,
    app_id            BIGINT       NOT NULL,
    session_id        BIGINT,
    model             VARCHAR(128) NOT NULL DEFAULT '',
    prompt_tokens     INT          NOT NULL DEFAULT 0,
    completion_tokens INT          NOT NULL DEFAULT 0,
    total_tokens      INT          NOT NULL DEFAULT 0,
    latency_ms        INT          NOT NULL DEFAULT 0,
    create_time       TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_usage_tenant_time ON usage_record (tenant_id, create_time);
CREATE INDEX IF NOT EXISTS idx_usage_app ON usage_record (tenant_id, app_id);

CREATE TABLE IF NOT EXISTS audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL,
    user_id     BIGINT,
    username    VARCHAR(64)  NOT NULL DEFAULT '',
    action      VARCHAR(64)  NOT NULL,
    target_type VARCHAR(32)  NOT NULL DEFAULT '',
    target_id   BIGINT,
    detail      TEXT         NOT NULL DEFAULT '',
    create_time TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_audit_tenant_time ON audit_log (tenant_id, create_time);
