-- 会话与消息
CREATE TABLE IF NOT EXISTS chat_session (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL,
    app_id      BIGINT       NOT NULL,
    title       VARCHAR(128) NOT NULL DEFAULT '',
    create_time TIMESTAMP    NOT NULL DEFAULT now(),
    update_time TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_chat_session_app ON chat_session (tenant_id, app_id);

CREATE TABLE IF NOT EXISTS chat_message (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL,
    session_id  BIGINT       NOT NULL,
    role        VARCHAR(16)  NOT NULL,
    content     TEXT         NOT NULL,
    create_time TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_chat_message_session ON chat_message (tenant_id, session_id);
