-- 应用（智能体）管理相关表
-- 全部业务表带 tenant_id，由 MyBatis-Plus 租户拦截器自动隔离。

CREATE TABLE IF NOT EXISTS app (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL,
    app_key     VARCHAR(64)  NOT NULL UNIQUE,
    name        VARCHAR(128) NOT NULL,
    description TEXT         NOT NULL DEFAULT '',
    icon_uri    VARCHAR(256) NOT NULL DEFAULT '',
    status      SMALLINT     NOT NULL DEFAULT 0,
    create_by   BIGINT,
    create_time TIMESTAMP    NOT NULL DEFAULT now(),
    update_time TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_app_tenant ON app (tenant_id);

CREATE TABLE IF NOT EXISTS model_provider_key (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT       NOT NULL,
    provider     VARCHAR(32)  NOT NULL,
    name         VARCHAR(128) NOT NULL,
    encrypted_key TEXT        NOT NULL,
    status       SMALLINT     NOT NULL DEFAULT 1,
    create_time  TIMESTAMP    NOT NULL DEFAULT now(),
    update_time  TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_mpk_tenant_provider ON model_provider_key (tenant_id, provider);

CREATE TABLE IF NOT EXISTS app_model_config (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT       NOT NULL,
    app_id         BIGINT       NOT NULL,
    provider       VARCHAR(32)  NOT NULL,
    model_name     VARCHAR(128) NOT NULL,
    provider_key_id BIGINT,
    temperature    DOUBLE PRECISION NOT NULL DEFAULT 0.7,
    max_tokens     INT          NOT NULL DEFAULT 2048,
    create_time    TIMESTAMP    NOT NULL DEFAULT now(),
    update_time    TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_amc_app ON app_model_config (tenant_id, app_id);

CREATE TABLE IF NOT EXISTS app_version (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT       NOT NULL,
    app_id       BIGINT       NOT NULL,
    version_no   INT          NOT NULL,
    workflow_dsl TEXT,
    model_snapshot TEXT,
    status       SMALLINT     NOT NULL DEFAULT 1,
    publish_by   BIGINT,
    publish_time TIMESTAMP,
    create_time  TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_av_app_version ON app_version (tenant_id, app_id, version_no);

CREATE TABLE IF NOT EXISTS app_api_key (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL,
    app_id      BIGINT       NOT NULL,
    key_hash    VARCHAR(64)  NOT NULL,
    name        VARCHAR(128) NOT NULL DEFAULT '',
    status      SMALLINT     NOT NULL DEFAULT 1,
    create_time TIMESTAMP    NOT NULL DEFAULT now(),
    expire_time TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_aak_app ON app_api_key (tenant_id, app_id);
