-- V6 组织模型：租户 → 组织树 → 用户 + 组织级角色授权（方案 C + 组织）
-- 设计说明：
--   * sys_organization 带 tenant_id，由 MyBatis-Plus 租户拦截器自动隔离（不在 IGNORE_TABLES 中）；
--   * sys_user 追加 org_id 列（V1 建表时未规划组织，V6 幂等补列）；
--   * sys_org_role 记录"组织-角色"关联，与 sys_user_role（用户-角色）共同构成权限来源：
--     用户权限 = 用户直接角色 ∪ 用户所属组织绑定的角色（组织继承）。

-- 组织表：parent_id=0 表示根组织，形成组织树
CREATE TABLE IF NOT EXISTS sys_organization (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL,
    parent_id   BIGINT       NOT NULL DEFAULT 0,     -- 0=根组织
    org_name    VARCHAR(128) NOT NULL,
    sort        INT          NOT NULL DEFAULT 0,
    status      SMALLINT     NOT NULL DEFAULT 1,     -- 1=启用
    create_time TIMESTAMP    NOT NULL DEFAULT now(),
    update_time TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_org_tenant ON sys_organization (tenant_id, parent_id);

-- 用户归属组织：V1 sys_user 无 org_id 列，V6 幂等追加（nullable，用户可不属于任何组织）
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS org_id BIGINT;

-- 组织-角色关联（组织级角色授权）
CREATE TABLE IF NOT EXISTS sys_org_role (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL,
    org_id      BIGINT       NOT NULL,
    role_id     BIGINT       NOT NULL,
    create_time TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_org_role ON sys_org_role (tenant_id, org_id, role_id);
